package com.dnd5e.gear;

public enum WeaponClass {
	UNARMED, CLUB, DAGGER, AXE, SPEAR, MACE, STAFF, SPECIAL, CROSSBOW, BOW, POLEARM, SWORD, SHIELD, AMMUNITION, ARCANE_FOCUS, DRUID_FOCUS, HOLY_SYMBOL
}