package com.starswonumber.deadnames;

public enum Nature {
	// TRANSHUMAN ABERRATIONS
	ASSIMILATIONIST, BODY_SHAPER, WORLD_SHAPER, LIVING_NETWORK, IDENTITY_POLICE, //
	STASIS_WORSHIPERS, MIND_SHAPER, REALITY_BENDER, SOCIAL_CANCER, TIME_BENDER, //
	// EXTRATERRESTRIAL SOJOURNS
	AMBASSADORS, COLONISTS, CONQUERORS, EXILED_ALIENS, EXPATRIOT_ALIENS, //
	PRISONERS_OF_WAR, RESOURCE_MINERS, SCHOLARLY_CONCLAVE, SPY_OUTPOST, WAYSTATION, //
	// SYNTHETIC PURPOSE

}
