package com.starswonumber.deadnames;

public enum Nature {
	// TRANSHUMAN ABERRATIONS
	ASSIMILATIONIST, BODY_SHAPER, WORLD_SHAPER, LIVING_NETWORK, IDENTITY_POLICE, //
	STASIS_WORSHIPERS, MIND_SHAPER, REALITY_BENDER, SOCIAL_CANCER, TIME_BENDER,
	// EXTRATERRESTRIAL SOJOURNS
	AMBASSADORS, COLONISTS, CONQUERORS, EXILED_ALIENS, EXPATRIOT_ALIENS, //
	PRISONERS_OF_WAR, RESOURCE_MINERS, SCHOLARLY_CONCLAVE, SPY_OUTPOST, WAYSTATION,
	// SYNTHETIC PURPOSE
	LAB_ACCIDENT, BELOVED_CHILD, LAW_ENFORCERS, EXPERIMENT, EMPTY_SHELL, //
	ENFORCED_EVOLUTION, ARTIFICIAL_WORKFORCE, TOOLS_OF_WAR, UTOPIAN_SLAVES, TORMENTED,
	// METADIMENSIONAL DEVIANCE
	EMOTION, ENERGY, ENTROPY, GRAVITY, MENTALITY, //
	PHYSICALITY, REPRODUCTION, TANGIBILITY, TEMPORALITY, VISIBILITY;

	private static Nature[] ABERRATIONS = { ASSIMILATIONIST, BODY_SHAPER, WORLD_SHAPER, LIVING_NETWORK, IDENTITY_POLICE,
			STASIS_WORSHIPERS, MIND_SHAPER, REALITY_BENDER, SOCIAL_CANCER, TIME_BENDER };
	private static Nature[] SOJOURNS = { AMBASSADORS, COLONISTS, CONQUERORS, EXILED_ALIENS, EXPATRIOT_ALIENS,
			PRISONERS_OF_WAR, RESOURCE_MINERS, SCHOLARLY_CONCLAVE, SPY_OUTPOST, WAYSTATION };
	private static Nature[] PURPOSES = { LAB_ACCIDENT, BELOVED_CHILD, LAW_ENFORCERS, EXPERIMENT, EMPTY_SHELL,
			ENFORCED_EVOLUTION, ARTIFICIAL_WORKFORCE, TOOLS_OF_WAR, UTOPIAN_SLAVES, TORMENTED };
	private static Nature[] DEVIANCES = { EMOTION, ENERGY, ENTROPY, GRAVITY, MENTALITY, PHYSICALITY, REPRODUCTION,
			TANGIBILITY, TEMPORALITY, VISIBILITY };

	/*
	 * STATIC METHODS
	 */
	public static Nature[] aberrations() {
		return ABERRATIONS;
	}

	public static Nature[] sojourns() {
		return SOJOURNS;
	}

	public static Nature[] purposes() {
		return PURPOSES;
	}

	public static Nature[] deviances() {
		return DEVIANCES;
	}
}
