package com.norvendae.rules.t1e;

public enum Skill {
	// blades and polearms
	DAGGER, BLADE, FOIL, SWORD, CUTLASS, BROADSWORD, BAYONET, SPEAR, HALBERD, PIKE, CUDGEL,
	// longarms
	BODY_PISTOL, AUTO_PISTOL, REVOLVER, CARBINE, RIFLE, AUTO_RIFLE, SHOTGUN, SUBMACHINE_GUN, LASER_CARBINE, LASER_RIFLE,
	//
	AIR_VEHICLES, LAND_VEHICLES, PILOT, SHIPS_BOAT, VEHICLE,
	//
	FORWARD_OBSERVER, // calls on artillery
	GUNNERY, // ... ?
	//
	ADMINISTRATION, BRIBERY, COMPUTER, ELECTRONICS, ENGINEERING, FORGERY, GAMBLING, JACK_OF_ALL_TRADES,
	LEADERSHIP, MECHANICAL, MEDICAL, XENOBIOLOGY, NAVIGATION, STEWARD, STREETWISE, TACTICS, VACC_SUIT, 
}
