import java.util.EnumSet;

public interface Option {
	public enum Feature {
		// ability bonus
		ABILITY_BONUS_4, ABILITY_BONUS_6, ABILITY_BONUS_8, ABILITY_BONUS_10, ABILITY_BONUS_12, ABILITY_BONUS_14, ABILITY_BONUS_16, ABILITY_BONUS_19,
		// strength bonus
		STR_BONUS_4, STR_BONUS_6, STR_BONUS_8, STR_BONUS_10, STR_BONUS_12, STR_BONUS_14, STR_BONUS_16, STR_BONUS_19,
		// dexterity bonus
		DEX_BONUS_4, DEX_BONUS_6, DEX_BONUS_8, DEX_BONUS_10, DEX_BONUS_12, DEX_BONUS_14, DEX_BONUS_16, DEX_BONUS_19,
		// constitution bonus
		CON_BONUS_4, CON_BONUS_6, CON_BONUS_8, CON_BONUS_10, CON_BONUS_12, CON_BONUS_14, CON_BONUS_16, CON_BONUS_19,
		// intelligence bonus
		INT_BONUS_4, INT_BONUS_6, INT_BONUS_8, INT_BONUS_10, INT_BONUS_12, INT_BONUS_14, INT_BONUS_16, INT_BONUS_19,
		// wisdom bonus
		WIS_BONUS_4, WIS_BONUS_6, WIS_BONUS_8, WIS_BONUS_10, WIS_BONUS_12, WIS_BONUS_14, WIS_BONUS_16, WIS_BONUS_19,
		// charisma bonus
		CHA_BONUS_4, CHA_BONUS_6, CHA_BONUS_8, CHA_BONUS_10, CHA_BONUS_12, CHA_BONUS_14, CHA_BONUS_16, CHA_BONUS_19,
		// expertise
		EXPERTISE_ATHLETICS, EXPERTISE_ACROBATICS, EXPERTISE_SLEIGHT_OF_HAND, EXPERTISE_STEALTH, EXPERTISE_ARCANA, EXPERTISE_HISTORY, EXPERTISE_INVESTIGATION, EXPERTISE_NATURE, EXPERTISE_RELIGION, EXPERTISE_ANIMAL_HANDLING, EXPERTISE_INSIGHT, EXPERTISE_MEDICINE, EXPERTISE_PERCEPTION, EXPERTISE_SURVIVAL, EXPERTISE_DECEPTION, EXPERTISE_INTIMIDATION, EXPERTISE_PERFORMANCE, EXPERTISE_PERSUASION,
		/*
		 * GENERIC & SHARED FEATURES
		 */
		FIGHTING_STYLE, EXTRA_ATTACK_1, TIMELESS_BODY,
		/*
		 * BARBARIAN
		 */
		RAGE, RAGE_PER_DAY_2, RAGE_PER_DAY_3, RAGE_PER_DAY_4, RAGE_PER_DAY_5, RAGE_PER_DAY_6, RAGE_PER_DAY_99, RAGE_BONUS_2, RAGE_BONUS_3, RAGE_BONUS_4, UNARMORED_BARBARIAN, RECKLESS_ATTACK, DANGER_SENSE, FAST_MOVEMENT, FERAL_INSTINCT, BRUTAL_CRITICAL_1, RELENTLESS_RAGE, BRUTAL_CRITICAL_2, PERSISTENT_RAGE, BRUTAL_CRITICAL_3, INDOMITABLE_MIGHT, PRIMAL_CHAMPION,
		// berserker
		FRENZY, MINDLESS_RAGE, INTIMIDATING_PRESENCE, RETALIATION,
		// totem warrior
		SPIRIT_SEEKER, BEAR_SPIRIT_3, EAGLE_SPIRIT_3, WOLF_SPIRIT_3, BEAR_ASPECT_6, EAGLE_ASPECT_6, WOLF_ASPECT_6, SPIRIT_WALKER, BEAR_ATTUNEMENT_14, EAGLE_ATTUNEMENT_14, WOLF_ATTUNEMENT_14,
		/*
		 * BARD
		 */
		// FIXME - unused - BARD_CANTRIPS_2, BARD_CANTRIPS_3, BARD_CANTRIPS_4,
		RITUAL_CASTING_BARD, INSPIRATION_D6, JACK_OF_ALL_TRADES, SONG_OF_REST_D6, INSPIRATION_D8, FONT_OF_INSPIRATION, COUNTERCHARM, SONG_OF_REST_D8, INSPIRATION_D10, MAGICAL_SECRETS_10, SONG_OF_REST_D10, MAGICAL_SECRETS_14, INSPIRATION_D12, SONG_OF_REST_D12, MAGICAL_SECRETS_18, SUPERIOR_INSPIRATION,
		// lore college
		CUTTING_WORDS, MAGICAL_SECRETS_6, PEERLESS_SKILL,
		// valor college
		COMBAT_INSPIRATION, BATTLE_MAGIC,
		/*
		 * CLERIC
		 */
		RITUAL_CASTING_CLERIC, CHANNEL_DIVINITY_1, CHANNEL_DIVINITY_2, CHANNEL_DIVINITY_3, POTENT_SPELLCASTING_CLERIC, TURN_UNDEAD, DIVINE_INTERVENTION_10, DIVINE_INTERVENTION_20, DESTROY_UNDEAD_5, DESTROY_UNDEAD_8, DESTROY_UNDEAD_11, DESTROY_UNDEAD_14, DESTROY_UNDEAD_17,
		// domains
		DIVINE_DOMAIN_DEATH, DIVINE_DOMAIN_KNOWLEDGE, DIVINE_DOMAIN_LIFE, DIVINE_DOMAIN_LIGHT, DIVINE_DOMAIN_NATURE, DIVINE_DOMAIN_TEMPEST, DIVINE_DOMAIN_TRICKERY, DIVINE_DOMAIN_WAR,
		// death
		REAPER, TOUCH_OF_DEATH, INESCAPABLE_DESTRUCTION, DIVINE_STRIKE_DEATH, IMPROVED_REAPER,
		// knowledge
		BLESSINGS_OF_KNOWLEDGE, VISIONS_OF_THE_PAST, KNOWLEDGE_OF_THE_AGES, READ_THOUGHTS,
		// life
		DISCIPLE_OF_LIFE, PRESERVE_LIFE, BLESSED_HEALER, DIVINE_STRIKE_LIFE, SUPREME_HEALING,
		// light
		WARDING_FLARE, RADIANCE_OF_THE_DAWN, IMPROVED_FLARE, CORONA_OF_LIGHT,
		// nature
		CHARM_ANIMALS_AND_PLANTS, DAMPEN_ELEMENTS, DIVINE_STRIKE_NATURE, MASTER_OF_NATURE,
		// tempest
		WRATH_OF_THE_STORM, DESTRUCTIVE_WRATH, THUNDERBOLT_STRIKE, DIVINE_STRIKE_TEMPEST, STORMBORN,
		// trickery
		BLESSING_OF_THE_TRICKSTER, INVOKE_DUPLICITY, TRICKERY_CLOAK, DIVINE_STRIKE_TRICKERY, IMPROVED_DUPLICITY,
		// war
		WAR_PRIEST, GUIDED_STRIKE, WAR_GODS_BLESSING, DIVINE_STRIKE_WAR, AVATAR_OF_BATTLE,
		/*
		 * DRUID
		 */
		RITUAL_CASTING_DRUID, WILD_SHAPE_2, WILD_SHAPE_4, WILD_SHAPE_8, BEAST_SPELLS, ARCHDRUID,
		// land circle
		NATURAL_RECOVERY, CIRCLE_SPELLS_ARCTIC, CIRCLE_SPELLS_COAST, CIRCLE_SPELLS_DESERT, CIRCLE_SPELLS_, CIRCLE_SPELLS_FOREST, CIRCLE_SPELLS_GRASSLAND, CIRCLE_SPELLS_MOUNTAIN, CIRCLE_SPELLS_SWAMP, CIRCLE_SPELLS_UNDERDARK, LANDS_STRIDE, NATURES_WARD, NATURES_SANCTUARY,
		// moon circle
		COMBAT_WILD_SHAPE, MOON_SHAPE_2, MOON_SHAPE_6, MOON_SHAPE_9, MOON_SHAPE_12, MOON_SHAPE_15, MOON_SHAPE_18, PRIMAL_STRIKE, ELEMENTAL_SHAPE, THOUSAND_FORMS,
		/*
		 * FIGHTER
		 */
		SECOND_WIND, ACTION_SURGE_2, ACTION_SURGE_17, EXTRA_ATTACK_2, EXTRA_ATTACK_3, INDOMITABLE_1, INDOMITABLE_2, INDOMITABLE_3,
		// fighting style
		STYLE_ARCHERY, STYLE_DEFENSE, STYLE_DUELING, STYLE_GREAT_WEAPON, STYLE_PROTECTION, STYLE_TWO_WEAPON,
		// champion
		IMPROVED_CRITICAL, REMARKABLE_ATHLETE, ADDITIONAL_FIGHTING_STYLE, SUPERIOR_CRITICAL, SURVIVOR,
		// battle master
		COMBAT_SUPERIORITY, STUDENT_OF_WAR, KNOW_YOUR_ENEMY, RELENTLESS, SUPERIORITY_DICE_4, SUPERIORITY_DICE_5, SUPERIORITY_DICE_6, SUPERIORITY_D8, SUPERIORITY_D10, SUPERIORITY_D12,
		// maneuvers
		COMMANDERS_STRIKE, DISARMING_ATTACK, DISTRACTING_STRIKE, EVASIVE_FOOTWORK, FEINTING_ATTACK, GOADING_ATTACK, LUNGING_ATTACK, MANEUVERING_ATTACK, MENACING_ATTACK, PARRY, PRECISION_ATTACK, PUSHING_ATTACK, RALLY, RIPOSTE, SWEEPING_ATTACK, TRIP_ATTACK,
		// eldritch knight
		WEAPON_BOND, WAR_MAGIC, ELDRITCH_STRIKE, ARCANE_CHARGE, IMPROVED_WAR_MAGIC,
		/*
		 * MONK
		 */
		UNARMORED_MONK, MARTIAL_ARTS_D4, MARTIAL_ARTS_D6, MARTIAL_ARTS_D8, MARTIAL_ARTS_D10, MONK_MOVE_2, MONK_MOVE_6, MONK_MOVE_10, MONK_MOVE_14, MONK_MOVE_18, WALL_RUNNING, DEFLECT_MISSILES, SLOW_FALL, KI_STRIKE, EVASION, STILLNESS_OF_MIND, PURITY_OF_BODY, TONGUE_OF_SUN_MOON, PERFECT_SELF,
		// ki powers
		KI_POWERS, FLURRY_OF_BLOWS, PATIENT_DEFENSE, STEP_OF_THE_WIND, STUNNING_STRIKE, DIAMOND_SOUL, EMPTY_BODY,
		// open hand
		OPEN_HAND_TECHNIQUE, WHOLENESS_OF_BODY, TRANQUILITY, QUIVERING_PALM,
		// shadow
		SHADOW_ARTS, SHADOW_STEP, SHADOW_CLOAK, OPPORTUNIST,
		// four elements
		ELEMENTAL_ATTUNEMENT,
		// elemental disciplines
		BREATH_OF_WINTER_17, CLENCH_OF_NORTH_WIND_6, ETERNAL_MOUNTAIN_11, FANGS_OF_FIRE_SNAKE, FIST_OF_FOUR_THUNDERS, FIST_OF_UNBROKEN_AIR, FLAMES_OF_PHOENIX_11, GONG_OF_THE_SUMMIT_6, MIST_STANCE_11, RIDE_THE_WIND_11, RIVER_OF_HUNGRY_FLAME_17, RUSH_OF_GALE_SPIRITS, SHAPE_OF_FLOWING_RIVER, SWEEPING_CINDER_STRIKE, WATER_WHIP, WAVE_OF_ROLLING_EARTH_17,

		/*
		 * PALADIN
		 */
		DIVINE_SENSE, LAY_ON_HANDS,
		// devotion
		SACRED_WEAPON, TURN_THE_UNHOLY,
		// ancients
		NATURES_WRATH, TURN_THE_FAITHLESS,
		// vengeance
		ABJURE_ENEMY, VOW_OF_ENMITY,
		/*
		 * END OF FEATURES
		 */
		;

		protected static final Feature[] CIRCLE_SPELLS = { CIRCLE_SPELLS_ARCTIC, CIRCLE_SPELLS_COAST,
				CIRCLE_SPELLS_DESERT, CIRCLE_SPELLS_, CIRCLE_SPELLS_FOREST, CIRCLE_SPELLS_GRASSLAND,
				CIRCLE_SPELLS_MOUNTAIN, CIRCLE_SPELLS_SWAMP, CIRCLE_SPELLS_UNDERDARK };

		protected static final Feature[] STR_BONUSES = { STR_BONUS_4, STR_BONUS_6, STR_BONUS_8, STR_BONUS_10,
				STR_BONUS_12, STR_BONUS_14, STR_BONUS_16, STR_BONUS_19 };
		protected static final Feature[] DEX_BONUSES = { DEX_BONUS_4, DEX_BONUS_6, DEX_BONUS_8, DEX_BONUS_10,
				DEX_BONUS_12, DEX_BONUS_14, DEX_BONUS_16, DEX_BONUS_19 };
		protected static final Feature[] CON_BONUSES = { CON_BONUS_4, CON_BONUS_6, CON_BONUS_8, CON_BONUS_10,
				CON_BONUS_12, CON_BONUS_14, CON_BONUS_16, CON_BONUS_19 };
		protected static final Feature[] INT_BONUSES = { INT_BONUS_4, INT_BONUS_6, INT_BONUS_8, INT_BONUS_10,
				INT_BONUS_12, INT_BONUS_14, INT_BONUS_16, INT_BONUS_19 };
		protected static final Feature[] WIS_BONUSES = { WIS_BONUS_4, WIS_BONUS_6, WIS_BONUS_8, WIS_BONUS_10,
				WIS_BONUS_12, WIS_BONUS_14, WIS_BONUS_16, WIS_BONUS_19 };
		protected static final Feature[] CHA_BONUSES = { CHA_BONUS_4, CHA_BONUS_6, CHA_BONUS_8, CHA_BONUS_10,
				CHA_BONUS_12, CHA_BONUS_14, CHA_BONUS_16, CHA_BONUS_19 };

		protected static final Feature[] EXPERTISE = { EXPERTISE_ATHLETICS, EXPERTISE_ACROBATICS,
				EXPERTISE_SLEIGHT_OF_HAND, EXPERTISE_STEALTH, EXPERTISE_ARCANA, EXPERTISE_HISTORY,
				EXPERTISE_INVESTIGATION, EXPERTISE_NATURE, EXPERTISE_RELIGION, EXPERTISE_ANIMAL_HANDLING,
				EXPERTISE_INSIGHT, EXPERTISE_MEDICINE, EXPERTISE_PERCEPTION, EXPERTISE_SURVIVAL, EXPERTISE_DECEPTION,
				EXPERTISE_INTIMIDATION, EXPERTISE_PERFORMANCE, EXPERTISE_PERSUASION };

		protected static final Feature[] FIGHTER_STYLE = { STYLE_ARCHERY, STYLE_DEFENSE, STYLE_DUELING,
				STYLE_GREAT_WEAPON, STYLE_PROTECTION, STYLE_TWO_WEAPON };

		protected static final Feature[][] ELEMENTAL_DISCIPLINE = {
				{ FANGS_OF_FIRE_SNAKE, FIST_OF_FOUR_THUNDERS, FIST_OF_UNBROKEN_AIR, RUSH_OF_GALE_SPIRITS,
						SHAPE_OF_FLOWING_RIVER, SWEEPING_CINDER_STRIKE, WATER_WHIP },
				{ CLENCH_OF_NORTH_WIND_6, GONG_OF_THE_SUMMIT_6 },
				{ ETERNAL_MOUNTAIN_11, FLAMES_OF_PHOENIX_11, MIST_STANCE_11, RIDE_THE_WIND_11 },
				{ BREATH_OF_WINTER_17, RIVER_OF_HUNGRY_FLAME_17, WAVE_OF_ROLLING_EARTH_17 } };

	}

	/*
	 * STATIC METHODS
	 * 
	 */
	public static void addElementalDiscipline(int toAdd, Actor actor) {
		int level = actor.getLevel();

		EnumSet<Feature> features;
		if (actor.getFeatures() == null)
			features = EnumSet.noneOf(Feature.class);
		else
			features = actor.getFeatures();

		Feature[] array;
		if (level >= 17)
			array = Feature.ELEMENTAL_DISCIPLINE[3];
		else if (level >= 11)
			array = Feature.ELEMENTAL_DISCIPLINE[2];
		else if (level >= 6)
			array = (Dice.roll(2) == 1) ? Feature.ELEMENTAL_DISCIPLINE[1] : Feature.ELEMENTAL_DISCIPLINE[0];
		else
			array = Feature.ELEMENTAL_DISCIPLINE[0];

		int added = 0;
		Feature candidate;
		while (added < toAdd) {
			candidate = Dice.randomFromArray(array);

			if (features.add(candidate))
				++added;
		}

		actor.setFeatures(features);
	}

}
